# Generated by Django 4.0.3 on 2024-05-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='break_time',
            field=models.CharField(default='', max_length=20, verbose_name='브레이크 타임'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='23:59', verbose_name='영업 종료 시간'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isPackaging',
            field=models.BooleanField(default=False, verbose_name='포장 가능 여부'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isParking',
            field=models.BooleanField(default=False, verbose_name='주차 가능 여부'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isPet',
            field=models.BooleanField(default=False, verbose_name='반려동물 동반 가능 여부'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isValet',
            field=models.BooleanField(default=False, verbose_name='발렛파킹 가능 여부'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(default='', verbose_name='메뉴 URL'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default='00:00', verbose_name='영업 시작 시간'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(max_length=10, verbose_name='휴일'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='food_category',
            field=models.CharField(max_length=30, verbose_name='음식 카테고리'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_link',
            field=models.CharField(max_length=500, verbose_name='이미지 링크 목록'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(max_length=200, verbose_name='가게 소개'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='local_category',
            field=models.CharField(max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_day',
            field=models.CharField(max_length=10, verbose_name='영업일'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(max_length=30, verbose_name='상호명'),
        ),
    ]
