# Generated by Django 4.0.3 on 2024-05-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_menu_price_remove_menu_title_menu_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='break_time',
            field=models.CharField(default='', max_length=20, verbose_name='브레이크 타임'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(default='', max_length=10, verbose_name='휴일'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(default='', max_length=200, verbose_name='가게 소개'),
        ),
    ]
