# Generated by Django 4.0.3 on 2024-05-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='break_time',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='브레이크 타임'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='휴일'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='가게 소개'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
    ]
