# Generated by Django 4.0.3 on 2024-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_break_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imgfile_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지1'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imgfile_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지2'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imgfile_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지3'),
        ),
    ]
