# Generated by Django 4.0.3 on 2024-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_imgfile_1_restaurant_imgfile_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default='37.5445023983984', verbose_name='위치 위도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default='127.056090471223', verbose_name='위치 경도'),
        ),
    ]
