# Generated by Django 4.0.3 on 2024-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='parking_area',
            field=models.CharField(default='', max_length=100, verbose_name='주차장소추천'),
        ),
    ]
